### ISSUE TITLE
I need this information in real time pls

### ISSUE THREAD

**Issue by cristo1985** [md-sohrab-alam/android-obd-reader#15]
Hi,
How do I make it read in real time the following parameters I need: turn signals light status (right or left or both), low beam light (dipped light), brake, battery voltage, belt of security, open door, position lights , high beam lights, speed, rpm km tripped on current day (that will reset on each app lunch), gear reverse (R), gear in neutral (N) and keep walking (D)?

I've made this interface for android. 
Thanks.
![Screenshot_20210510-142004_CruscottoGPS](https://user-images.githubusercontent.com/13002905/117658890-8c7d4800-b19b-11eb-854e-e1ec2c34edad.jpg)

**Comment by md-sohrab-alam** [comment]
This library support standard PIDs and based on these, I have calculated some trip information only.
